en:
  languageName: English
  weight: 10
  menu:
    main:
    - identifier: home
      name: Home
      url: "#hero"
      weight: 10
    - identifier: about
      name: About
      url: "#about-us"
      weight: 20
    - identifier: features
      name: Features
      url: "#features"
      weight: 30
    - identifier: screenshots
      name: Screenshots
      url: "#screenshots"
      weight: 40
    - identifier: team
      name: Team
      url: "#team"
      weight: 50
    - identifier: pricing
      name: Pricing
      url: "#pricing"
      weight: 60
    - identifier: blog
      name: Blog
      url: "#blog"
      weight: 70
    - identifier: contact
      name: Contact
      url: "#contact"
      weight: 80
  params:
    navigation:
      help: Help

es:
  languageName: Español
  weight: 20
  menu:
    main:
    - identifier: home
      name: Inicio
      url: "#hero"
      weight: 10
    - identifier: about
      name: Acerca
      url: "#about"
      weight: 20
    - identifier: features
      name: Características
      url: "#features"
      weight: 30
    - identifier: screenshots
      name: Capturas
      url: "#screenshots"
      weight: 40
    - identifier: team
      name: Equipo
      url: "#team"
      weight: 50
    - identifier: pricing
      name: Precios
      url: "#pricing"
      weight: 60
    - identifier: blog
      name: Blog
      url: "#blog"
      weight: 70
    - identifier: contact
      name: Contacto
      url: "#contact"
      weight: 80
  params:
    navigation:
      help: Ayuda
