main:
- identifier: home
  name: Home
  url: /
  weight: 10
- identifier: about
  name: About
  url: "#about"
  weight: 20
- identifier: features
  name: Features
  url: "#features"
  weight: 30
- identifier: screenshots
  name: Screenshots
  url: "#screenshots"
  weight: 40
- identifier: team
  name: Team
  url: "#team"
  weight: 50
- identifier: pricing
  name: Pricing
  url: "#pricing"
  weight: 60
- identifier: post
  name: Posts
  url: "#post"
  weight: 70
- identifier: contact
  name: Contact
  url: "#contact"
  weight: 80
